name: Build (Manual)

on: [workflow_dispatch]

jobs:
  build_wheels_py312:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: cp312*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
